name: lovelystay-e2e

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    networks:
      - e2e-network
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    networks:
      - e2e-network
    volumes:
      - ./src:/app/src
    depends_on:
      - db
networks:
  e2e-network:
    driver: bridge
